### ISSUE TITLE
本番環境のネットワーク構成によっては通信方式を変える必要がある

### ISSUE THREAD

**Issue by uesugi6111** [cafecoder-dev/cafecoder-rs#18]
現在docker で立ち上げたコンテナとの通信に、inspectで取得したipアドレスを使用しています。
しかしこのIPアドレスは通常の設定ではdocker のデフォルトネットワーク内のIPアドレスを指します。
よってDocker が動いているhost PCで Judgeを起動した場合、対象のコンテナのIPアドレスを指定しても通信できません。

開発環境としてはDocker で立ち上げたコンテナ内からJudgeを起動し、host PCのDocker を使用し、Docker のデフォルトネットワーク内にコンテナを生成していました。
もしJudgeを起動するのが ホストPCであればIPアドレスを指定し、ポートのフォワーディングを行わないと通信できないと思うのですがどうなっていますか？
go のソースでも大体同じに見えていて混乱しています。

**Comment by earlgray283** [comment]
ちょっと検証用のコンテナとか立ててみますが、go のソースでもホストとコンテナの TCP 通信が `$ docker inspect` の `IPAddress` でできていました。

**Comment by uesugi6111** [comment]
こちら通っているようで不思議
