### ISSUE TITLE
独自エラー型について、thiserror もしくは anyhow クレートの利用を検討する

### ISSUE THREAD

**Issue by magurotuna** [cafecoder-dev/cafecoder-rs#3]
今の `src/error.rs` は以下のようになっており、依存クレートが吐くエラーを独自エラー型でラップしている

```rust
#[derive(Debug)]
pub enum Error {
    SqlxError { e: sqlx::Error },
    BollardError { e: bollard::errors::Error },
}

impl From<sqlx::Error> for Error {
    fn from(e: sqlx::Error) -> Self {
        Error::SqlxError { e }
    }
}

impl From<bollard::errors::Error> for Error {
    fn from(e: bollard::errors::Error) -> Self {
        Error::BollardError { e }
    }
}
```

このパターンを使う場合は [`thiserror`](https://docs.rs/thiserror/1.0.23/thiserror/) クレートを使うのがデファクトスタンダートになっているため、これの利用を検討する。
もしくは、独自エラー型をわざわざ用意するほど厳密なハンドリングが必要ないのであれば、[`anyhow`](https://docs.rs/anyhow/1.0.36/anyhow/) を利用するのがよさそう

**Comment by earlgray283** [comment]
エラー型のラッパーがあるのは知りませんでした・・。それを使うようにしましょう。

**Comment by earlgray283** [comment]
そこらへんの便利クレートがあるのは知りませんでした・・。
パット見だと `thiserror` と `anyhow` の違いがあまりよくわからないので maguro さんに任せたいです。
