### ISSUE TITLE
docker api を叩く

### ISSUE THREAD

**Issue by earlgray283** [cafecoder-dev/cafecoder-rs#7]
対応する go のソースは [こちら](https://github.com/cafecoder-dev/cafecoder-judge/blob/master/src/dkrlib/dkrlib.go)
「コンテナを作る」と「コンテナを消す」だけできれば ok です。
[bollard](https://crates.io/crates/bollard) クレートを使えば良さそう・・？

**Comment by earlgray283** [comment]
https://github.com/cafecoder-dev/cafecoder-rs/blob/main/src/docker_lib.rs

**Comment by uesugi6111** [comment]
こちらもしかして終わっていますか?
「コンテナを作る」と「コンテナを消す」が有りそうに見えるので

**Comment by earlgray283** [comment]
@uesugi6111 
返信遅れてしまってすみません。
一応作るだけ作ってみただけで、まだテストなどが不十分なので issue として残しているという感じです。
